# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 747)
        MainWindow.setStyleSheet("#centralwidget{\n"
"background-color: #2b2d33;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 599))
        self.tableWidget.setMaximumSize(QtCore.QSize(40000, 40000))
        self.tableWidget.setStyleSheet("/* Genel Widget Stilleri */\n"
"QWidget {\n"
"    background-color: #282a36;\n"
"    color: #abb2bf;\n"
"    font-family: \"Myanmar Text\", monospace;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* Table Widget Stilleri */\n"
"QTableWidget {\n"
"    border: 1px solid #333740;\n"
"    gridline-color: #333740;\n"
"    selection-background-color: #44475a;\n"
"    selection-color: #abb2bf;\n"
"}\n"
"\n"
"/* Başlık Satırı Stilleri */\n"
"QHeaderView {\n"
"    background-color: #333740;\n"
"    color: #abb2bf;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Hücre Stilleri */\n"
"QTableWidgetItem {\n"
"    border: 1px solid #333740;\n"
"    padding: 4px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"/* Alternatif Satır Renklendirme */\n"
"QTableWidget::item:alternate {\n"
"    background-color: #2b2d33;\n"
"}\n"
"\n"
"/* Seçili Hücre Stilleri */\n"
"QTableWidget::item:selected {\n"
"    background-color: #44475a;\n"
"    color: #abb2bf;\n"
"}\n"
"\n"
"/* Scrollbar Stilleri */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #333740;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #44475a;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: #333740;\n"
"    height: 10px;\n"
"    subcontrol-position: bottom;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: #333740;\n"
"    height: 10px;\n"
"    subcontrol-position: top;\n"
"}\n"
"\n"
"/* Köşe Genişletme Butonu Stilleri */\n"
"QAbstractScrollArea::cornerWidget {\n"
"    background-color: #333740;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    column-spacing: 10px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    width: 100px;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget_2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lcdNumber)
        self.line = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(30, 30))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ask"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time Interval"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
